### PR TITLE
Minor fix for the options output message.

### PR DESCRIPTION
**Pull request by raravena80**
# Issue Type

- Bugfix Pull Request

## Summary

This is a very minor fix for the options parsing. It's a leftover from https://github.com/cristim/autospotting/pull/120

## Code contribution checklist

1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [x] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [x] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [x] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by raravena80** [comment]
@cristim looks like the build is failing because of 
```
/usr/local/go/src/github.com/cristim/ec2-instances-info
```

**Comment by cristim** [comment]
@raravena80 that shouldn't cause this, I suspect it's the latest change in https://github.com/eawsy/aws-lambda-go-shim which I think changed some things about handling of the GOPATH variable.

@fsenart, does this look familiar? https://travis-ci.org/cristim/autospotting/builds/269340055?utm_source=github_status&utm_medium=notification

**Comment by fsenart** [comment]
@cristim in order to be compliant with the new Go policy which sets a default GOPATH to $HOME/go and to be able to handle multiple GOPATHs, we've removed the default GOPATH=/go from the docker image. Also your build will pass if you add `-e GOPATH=/go` to the `docker run` command. Sorry for the inconvenience.

**Comment by cristim** [comment]
Thanks @fsenart, that did the trick!

**Comment by cristim** [comment]
@raravena80 let's abandon this, I already applied this change in #135

**Pull request closed without merging**
