### PR TITLE
 iam: add 'CreateServiceLinkedRole' to permissions 

### PR DESCRIPTION
**Pull request by xlr-8**
# Issue Type

- Bugfix Pull Request

## Summary

This permission seems required in order to have autospotting running fine
with CodeDeploy and ECS in order to avoid facing AuthFailure errors.

In order to eventually make it easier to work with terraform, the
autospotting_role's name has been exported.

Closes: https://github.com/cristim/autospotting/issues/187

## Code contribution checklist

1. [x] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [x] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [x] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [x] No issues are reported when running `make full-test`.
1. [x] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by cristim** [comment]
I couldn't reproduce this issue, is this still a problem for you guys?

**Comment by twoism-dev** [comment]
Hi @cristim 

Sorry for the late response - this fix works for myself and @homme at FATMAP

Would it be possible to merge?

Ben

**Comment by cristim** [comment]
@twoism-dev, @homme: I know the fix works.

My point was that it may have already been fixed by AWS in the meantime so fixing it on our side is redundant.

I'd like to see if there's anyone else out there having this issue on a fresh installation.

**Comment by twoism-dev** [comment]
@cristim 

Yes - I've just provisioned a new environment with the latest version of autospotting - and had the same issue, which was fixed by this commit.

**Comment by cristim** [comment]
Fair enough, thanks for reporting it.

**Pull request merged**
