### PR TITLE
Support the allowed_instance_types option for terraform

### PR DESCRIPTION
**Pull request by binarylogic**
# Issue Type

- Feature Pull Request

## Summary

Supports the `allowed_instance_types` option for Terraform.

Closes https://github.com/cristim/autospotting/issues/191
Refs https://github.com/cristim/autospotting/issues/47
Refs https://github.com/cristim/autospotting/pull/120

EDIT: That should also close Closes https://github.com/cristim/autospotting/issues/121 - with some documentaiton

## Code contribution checklist

1. [x] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [x] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [x] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [x] No issues are reported when running `make full-test`.
1. [x] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by binarylogic** [comment]
Interestingly, I added the `ALLOWED_INSTANCE_TYPES`  environment variable manually to my lambda function and it did not work as expected. Is there something I'm missing to get this to work properly? It's already defined in the cloudformation template.

**Comment by cristim** [comment]
This feature hasn't been tested much, if at all, so I wouldn't be surprised if it it's incorrectly wired into the configuratio or even broken. 

It would be great if you could try it out and get it work and as a bonus make it configurable on a per group basis using tags.

**Comment by binarylogic** [comment]
Sure, I'll try to take care of both, and I've confirmed that this feature does not work.

**Comment by CpuID** [comment]
Nitpick along the way: https://github.com/cristim/autospotting/blob/master/core/autoscaling_test.go#L2918

`s/Instace/Instance` :) Might as well include it here if things are being fixed up.

**Comment by xlr-8** [comment]
@binarylogic did you get a chance to test the feature further? If we're going to integrate it, we might as well just fix it.

Changes so far look good to me, could be nice to integrate [this](https://github.com/cristim/autospotting/pull/192#pullrequestreview-86095877) and [that comment](https://github.com/cristim/autospotting/pull/192#issuecomment-355185732).

**Comment by cristim** [comment]
Wasn't this also done as part of #204?

Or are we missing anything?

**Comment by CpuID** [comment]
Didn't https://github.com/cristim/autospotting/pull/204 cover disallowed instance types? This PR is for allowed instance types.

**Comment by cristim** [comment]
@CpuID you're right, I just noticed that while resolving the merge conflicts.

**Comment by xlr-8** [comment]
To me the idea is also to fix the functioning of this option

**Comment by cristim** [comment]
@xlr-8 you're saying that we now only have code for the disallow logic?

**Comment by xlr-8** [comment]
@cristim yes - I'm saying, I fixed the "disallowed" logic and never tried the "allowed" one, so despite having the code I cannot vouch for it.

**Comment by cristim** [comment]
Okay, I'll try to test this feature over the week-end if nobody does it before and gives a concrete status here.

**Comment by xlr-8** [comment]
I assume you merged following your test, or did I miss something else in the meantime?

**Comment by cristim** [comment]
Honestly I didn't actually test this, but it was sitting there for too much so I decided to just take the chance and merge it.

I'm lately trying to outsource the testing of some features to the users in the wild and then fix it quickly if anything breaks. I recently did this with a few other changes, where small issues that creeped in were found and fixed very fast and then everyone benefited from them, rather than waiting for weeks until we can test it before getting merged.

**Comment by xlr-8** [comment]
Fair enough

**Pull request merged**
