### PR TITLE
Handle #48 in short-term by using appropriate securitygroup form

### PR DESCRIPTION
**Pull request by ahaverbuch**
# Issue Type #

- Bugfix Pull Request

## Summary ##

Per discussion in #48, we need SecurityGroupId support for non-VPC. This flips between SecurityGroups and SecurityGroupId based off of "sg-", which while not perfect, is a good midterm solution

Confirmed it works in our scenario.

### CODE REVIEW

**Comment by cristim** [comment]
I think whoever names his SGs starting with `sg-` is asking for trouble and doing it this way should be good enough for the vast majority of the users. It's also simple to implement, which is a huge plus.

We should just document this as a known issue.

**Comment by xlr-8** [comment]
@cristim @ahaverbuch - sorry in advance for "being that guy" 
Just adding my 2 cents, I'm not a big fan of the 'temporary-fix' or 'mid-term solution' - if the problem isn't really tricky. From what I understood it wouldn't be that complicated to implement a management of both, no? If so, why hasn't this been done, nor issue created/documentation updated to specify the limitation of "sg-" security groups?

**Comment by cristim** [comment]
@xlr-8 this was a quite nasty issue that rendered it entirely useless for a considerable number of users having that certain configuration.

In such cases I prefer to have a quick fix that works for 99+% of the users, if possible, and implement the proper fix afterwards without any pressure to deliver.

I'm not sure the proper fix is as trivial in this case as it may seem, unfortunately I didn't have to take care of it yet.

Patches are welcome, as always :-)

**Comment by xlr-8** [comment]
Yes, I can understand.

Also I would mitigate the number of users impacted by it, except if you have statistics (?).
As for a matter of facts, you opened the issue in November, and nobody else "up" it, except me by curiosity, so until recently, people might have been affected without saying anything, but that didn't seem as such a "big problem" to me.

As usual, I'd be happy to help but have been pretty busy lately, hope it will go better soon enough.

**Comment by cristim** [comment]
I've seen it on one of my accounts classic but didn't have time to handle it, @ahaverbuch saw it as well and I think there was someone else who mentioned it a longer while back.

Considering the currently small userbase, I think it's enough to expedite this fix to avoid first use problems with any other new users.

**Pull request merged**
