### PR TITLE
use TerminateInstanceInAutoScalingGroup instead of Detach

### LINKED ISSUE #138: detachAndTerminateOnDemandInstance should use TerminateInstanceInAutoScalingGroup
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

The current logic issues a detach followed by a termination.
`TerminateInstanceInAutoScalingGroup` would do these for us, slightly simplifying the replacement logic.

### PR DESCRIPTION
**Pull request by rgarcia**
# Issue Type

- Feature Pull Request

## Summary

Fixes #138

## Code contribution checklist

1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by cristim** [comment]
@rgarcia thanks for this contribution!

It seems the tests are failing, please look into it: https://travis-ci.org/cristim/autospotting/jobs/272569257

Feel free to reach out on Gitter if you need any help.

**Comment by rgarcia** [comment]
fixed the tests

**Comment by cristim** [comment]
Thanks @rgarcia, I'll look into this ASAP.

**Comment by cristim** [comment]
Thanks @rgarcia for this contribution!

**Comment by vecchp** [comment]
Is this still a feature that is desired? I may pick it up in a sprint or two as we want autospotting to respect lifecycle hooks.

**Comment by cristim** [comment]
Sure,I will gladly accept a PR as long as it's tested and doesn't introduce serious regressions

**Pull request merged**
