### PR TITLE
Revert "Add a disallowed-instance-types option"

### PR DESCRIPTION
**Pull request by cristim**
Reverts cristim/autospotting#196

### CODE REVIEW

**Comment by cristim** [comment]
I tried to revert this so we can polish it further, but it's too messy.

@binarylogic please create another PR to address @xlr-8's concerns expressed in #196

**Comment by binarylogic** [comment]
Whoa. I _definitely_ do not agree with reverting this. Why wouldn't we open a separate PR to address the issues? None of the issues raised were major bugs or breaking changes, they were nice to haves, nor do I think all of them are valid.

**Comment by cristim** [comment]
I thought reverting will allow us to work forward on the same PR, didn't realize it will create yet another one.

But yeah, let's create a new one for more polishing.

**Comment by binarylogic** [comment]
Other than the comment typo I don't think we should make any of the changes suggested. The behavior across both options should be addressed in a separate PR as recommended in your code contribution checklist:

> The contribution fixes a single existing github issue, and it is linked to it.

What exactly do you think should be changed?

**Comment by cristim** [comment]
I commented on the pull request, but basically what @xlr-8 said.

If you look at the issue in which I first described the problem and how I would like to have it implemented, there were many aspects that never made it to that PR, pretty much because of misunderstandings with the other contributor who implemented it. 

After a lot of ping-pong during the review we all just got tired of it and I decided to just merge whatever we had at that point, hoping that someone else would be willing to finish the work. That's why it wasn't tested nor properly exposed in the configuration.

**Pull request closed without merging**
